config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'games#index'
  resources :games do
    collection do
      get 'search'
      get 'all'
    end
    resources :comments, only: :create
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :game
  belongs_to :user
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :images, dependent: :destroy
  belongs_to :user
  has_many :comments, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true

  def self.search(search)
    if search
      Game.where('name LIKE(?)', "%#{search}%")
    else
      Game.all
    end
  end
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :src, ImageUploader
  belongs_to :game, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :games
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/games/#{comment.game.id}"
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, game_id: params[:game_id])
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def index 
    @games_all = Game.includes(:images).order('created_at DESC')
    @games = @games_all [0..19]

  end

  def all
    @games = Game.includes(:images)
  end
  
  def new
    @game = Game.new
    @game.images.new
  end

  def create
    @game = Game.new(game_params)
    if @game.save!
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @game = Game.find(params[:id])
    @image = @game.images
    @comment = Comment.new
    @comments = @game.comments.includes(:user)
  end

  def destroy
    @game = Game.find(params[:id])
    if @game.destroy
      redirect_to root_path
    else 
      render :show
    end
  end

  def search
    @games = Game.search(params[:keyword]).order("created_at DESC")
  end

  # def edit
  #   @game = Game.find(params[:id])
  #   @image = @game.images
  # end

  # def update
  #   @game = Game.find(params[:id])
  #   if @game.update(game_params)
  #     redirect_to root_path
  #   else 
  #     render :show
  #   end
  # end

  private

  def game_params
    params.require(:game).permit(:name, :text, :platform, images_attributes: [:src]).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.haml
.NewWrapper
  = form_for @game, class: "NewWrapper__Form"do |f|
    %br ゲーム画像
    = f.fields_for :images do |i|
      = i.file_field :src
    %br ゲーム名
    = f.text_field :name, placeholder: "ゲームタイトル",class: "NewWrapper__Form--title"
    %br プラットフォーム
    = f.text_field :platform, placeholder: "例: PS4 switch PC等",class: "NewWrapper__Form--title"
    %br ゲーム説明
    = f.text_area :text, placeholder: "ゲームについてや背景について記述してください　　例:モンスターを倒してレベルアップをして強くなるゲームです。　　　　　　　　　　　　　　　　　　　この一枚は、最後の一撃を決める直前の瞬間です。",class: "NewWrapper__Form--text", type: "text"
    %br
    = f.submit "投稿",class: "NewWrapper__Form--btn"

app/views/games/_game.html.haml
= link_to game_path(game.id) do
  - game.images.each do |image|
    = image_tag image.src.url, class:"UpGame__Box--image", size: "640x480"

app/views/games/all.html.haml
.Wrapper
  .UpGame
    .UpGames
      %h2 【投稿一覧】
      .UpGames__Boxes
        = render @games

app/views/games/edit.html.haml
= render partial: 'form'

app/views/games/index.html.haml
.Wrapper
  .Main
    .MainImage
      .content
        %h2.content__title
          グラフィックでゲームを楽しもう！
        %br
        %p.content__text
          FGAMEでゲーム背景を共有しよう
          %br
          ゲームを景色から探してみよう！！
  .UpGame
    .UpGames
      %h2 【新着一覧】
      .UpGames__Boxes
        = render @games

app/views/games/new.html.haml
= render partial: 'form'

app/views/games/search.html.haml
.Wrapper
  .UpGame
    .UpGames
      %h2 【検索結果】
      .UpGames__Boxes
      - if @games.empty?
        .SearchGame
          該当するゲームはありません
      - else
        - @games.each do |game|
          = render partial: "game", locals: { game: game}

app/views/games/show.html.haml
.ShowWrapper
  .ShowMain
    .ShowMain__Image
      【ゲーム背景】
    - @image.each do |img|
      = image_tag img.src_url, size: "1280x720", class:"ShowMain__Image--Top"
    .ShowMain__Image1
      【ゲームタイトル】
    .ShowMain__Title
      = @game.name
    .ShowMain__Image2
      【プラットフォーム】
    .ShowMain__plat
      = @game.platform
    .ShowMain__Image3
      【このゲーム・写真について】
    .ShowMain__Text
      = safe_join(@game.text.split("\n"),tag(:br))
    - if user_signed_in? && current_user.id == @game.user_id
      .ShowBtn
        -# = link_to "編集する", edit_game_path(@game.id), class: "ShowBtn--edit"
        = link_to "削除する", game_path(@game.id), method: :delete,class: "ShowBtn--delete"
    .Comment
      【コメント】
    - if current_user
      = form_with(model: [@game, @comment], local: true, class: "Comment__Form", id:"new_comment") do |com|
        = com.text_area :text, placeholder: "誹謗中傷など他人が傷付くコメントはやめましょう", class:"CommentBox"
        = com.submit "送信", class: "CommentSubmit"
    .Comments
      【コメント一覧】
    - if @comments.empty?
      .Comments__none
        コメントはありません。
    - else
      - @comments.each do |comment|
        .Comments__main
          = comment.user.nickname
        .Comments__text
          = safe_join(comment.text.split("\n"),tag(:br))

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FGame
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application'
  %body
  = render'shared/header'
  = yield
  = render'shared/footer'

app/views/shared/_footer.html.haml
.footer
  .footer__logo
    © FGAME

app/views/shared/_header.html.haml
.header
  .header-content
    .main-header
      .header-icon
        = link_to image_tag("logo_game.png", size: "150x40"), root_path
      = form_with(url: search_games_path, local: true, method: :get, class: "search-box") do |form|
        = form.text_field :keyword, placeholder: "知ってるタイトルで検索", class: "class-serch__text"
        = form.submit "検索",class: "search-submit"
    .header-nav
      .right-list
        .right-list__mypage
          = link_to "投稿一覧",all_games_path,class:"right-list__link1" 
      - if user_signed_in?
        .right-list__mypage
          = link_to current_user.nickname,root_path,class:"right-list__link3" 
        .right-list__mypage
          = link_to destroy_user_session_path, method: :delete,class:"right-list__link" do
            ログアウト
        .right-list__mypage
          = link_to "投稿する",new_game_path,class:"right-list__link2" 
      - else
        .right-list__mypage
          = link_to "ログイン",user_session_path, class:"right-list__link" 
        .right-list__mypage
          = link_to "新規登録",new_user_registration_path, class:"right-list__link" 